### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by NinovanderMark** [Dekker3D/KBT#1]
As a curious passer-by I was interested what this project is about/for? There does not appear to be a README or repository description set yet. 😄

**Comment by Dekker3D** [comment]
Hah, hey again! This is an add-on for a long-dead MMO (Wildstar) for which I maintain a private server. It's not -my- add-on either, I'm just making tweaks to make it work better on servers based on https://github.com/NexusForever/NexusForever

You're right, maybe I should write up a readme.

**Comment by NinovanderMark** [comment]
Great stuff! I was just curious, but now I know. 😎👍
